"""Increase image_url length to 255

Revision ID: c3ec5ad559d7
Revises: 2fef3c5b98a0
Create Date: 2025-05-28 14:13:23.140731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3ec5ad559d7'
down_revision = '2fef3c5b98a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('news', schema=None) as batch_op:
        batch_op.drop_column('updated_at')

    # ### end Alembic commands ###
